# [START runtime]
runtime: java
env: flex

handlers:
- url: /.*
  script: ignored_field
  secure: always  # Require HTTPS

runtime_config:  # Optional
  jdk: openjdk8
  server: jetty9

manual_scaling:
  instances: 1
